name: icon-automation
on:
  push:
    branches:
      - master
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - package.json

jobs:
  icon_automation:
    name: figma icon automation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: yarn install
      - name: Figma Action
        uses: primer/figma-action@v1.0.0-alpha.3
        with:
          args: "format=svg outputDir=./src/"
        env:
          FIGMA_FILE_URL: ${{ secrets.FIGMA_FILE_URL }}
          FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
      - run: yarn generate
      - run: yarn build
      - run: yarn build-bundle
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v1.2.5
        with:
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: feishu bot notification
        uses: wangsijie/feishu-bot@v1
        with:
          uuid: 72469622-18ee-410c-bfd4-bbea8909c23a
          data: |
            {
              "msg_type": "post",
              "content": {
                  "post": {
                      "en_us": {
                          "title": "兄弟们，咱们的图标更新啦！",
                          "content": [
                              [
                                  {
                                      "tag": "text",
                                      "text": "请使用 yarn upgrade figma-vue-icon --latest 更新。 "
                                  },
                                  {
                                      "tag": "a",
                                      "text": "点击查看图标",
                                      "href": "https://baosisi07.github.io/figma-vue-icon/"
                                  }
                              ]
                          ]
                      }
                  }
              }
            }
